# Base model with Bidirectional Encoder Representations from Transformers (BERT)

In [1]:
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import seaborn as sns
from wordcloud import WordCloud,STOPWORDS
import missingno as msno
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from keras.preprocessing import text
import keras
from keras.models import Sequential
from keras.layers import Dense,Embedding,LSTM,Dropout
from keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.preprocessing.sequence import pad_sequences
import nltk
from nltk import word_tokenize
from nltk.stem import PorterStemmer
import torch
from torch.utils.data import Dataset
from transformers import BertTokenizer,BertTokenizerFast, BertForSequenceClassification
from transformers import TrainingArguments, Trainer, pipeline

2024-10-23 20:50:36.277280: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.

## Prepare Dataset

Load JSON file

In [2]:
def load_json_file(filename):
    with open(filename) as f:
        file=json.load(f)
    return file   
    
filename="intents.json"
intents=load_json_file(filename)
print(intents)

{'intents': [{'tag': 'greeting', 'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day', 'Whats up'], 'responses': ['Hello!', 'Hi there, how can I help?'], 'context_set': ['']}, {'tag': 'name', 'patterns': ['what is your name', 'what should I call you', 'whats your name?'], 'responses': ['You can call me bot.', "I'm bot!", "I'm bot."], 'context_set': ['']}, {'tag': 'problem_solving', 'patterns': ['i need help', 'help me', 'tell me', 'i have some problem', 'problem', 'can you help me?'], 'responses': ['yes i can help you', 'tell me what can i do for you', 'what do you want me to do', 'how can i help you', 'what kind of help do you need', 'tell me'], 'context_set': ['']}, {'tag': 'jaundice', 'patterns': ['yellow skin', 'yellowish white part of eye', 'itching of the skin', 'light colored stools', 'dark colored urine'], 'responses': ['you might be suffering from jaundice'], 'context_set': ['']}, {'tag': 'emotional problems', 'patterns': ['anxiety', 'depression fatigue', 'feeling tense', 'flashbacks and nightmares', 'disinterest in regular activities', 'suicidal thoughts', 'hallucinations', 'delusions'], 'responses': ['you might be suffering from emotional problems'], 'context_set': ['']}, {'tag': 'headache problems', 'patterns': [' dizziness', 'nausea', 'vomiting', 'inability to walk'], 'responses': ['you might be suffering from headache problems'], 'context_set': ['']}, {'tag': 'appendicitis', 'patterns': ['feeling sick (nausea)', 'being sick', 'loss of appetite', 'diarrhoea', 'a high temperature (fever) and a flushed face'], 'responses': ['you might be suffering from appendicitis'], 'context_set': ['']}, {'tag': 'anal cancer', 'patterns': ['bleeding from the bottom (rectal bleeding)', 'itching and pain around the anus', 'small lumps around the anus', 'a discharge of mucus from the anus', 'loss of bowel control '], 'responses': ['you might be suffering from anal cancer'], 'context_set': ['']}, {'tag': 'allergy', 'patterns': [' sneezing and an itchy, runny or blocked nose', 'itchy, red, watering eyes', 'wheezing, chest tightness, shortness of breath and a cough', 'a raised, itchy, red rash (hives)', 'swollen lips, tongue, eyes or face', 'tummy pain, feeling sick, vomiting or diarrhoea', 'dry, red and cracked skin'], 'responses': ['you might be suffering from allergy'], 'context_set': ['']}, {'tag': 'alcohol-related liver disease', 'patterns': [' abdominal pain', 'loss of appetite', 'fatigue', 'feeling sick', 'diarrhoea', 'feeling generally unwell', 'yellowing of the skin and whites of the eyes (jaundice)', 'swelling in the legs, ankles and feet, due to a build-up of fluid', 'swelling in your abdomen, due to a build-up of fluid known as ascites', 'a high temperature (fever) and shivering attacks', 'very itchy skin', 'hair loss', 'unusually curved fingertips and nails (clubbed fingers)', 'blotchy red palms', 'significant weight loss', 'weakness and muscle wasting', 'confusion and memory problems, trouble sleeping (insomnia) and changes in your personality due to a build-up of toxins in the brain', 'vomiting blood and black, tarry stools due to internal bleeding', 'a tendency to bleed and bruise more easily, such as frequent nosebleeds and bleeding gums', 'increased sensitivity to alcohol and drugs'], 'responses': ['you might be suffering from alcohol-related liver disease'], 'context_set': ['']}, {'tag': 'bladder cancer', 'patterns': [' a need to urinate on a more frequent basis', 'sudden urges to urinate', 'a burning sensation when passing urine'], 'responses': ['you might be suffering from bladder cancer'], 'context_set': ['']}, {'tag': 'dehydration', 'patterns': ['izziness', 'light headedness', 'headache', 'tiredness', 'dry mouth', 'dry lips', 'dry eyes', 'passing small amounts of urine infrequently'], 'responses': ['you might be suffering from dehydration'], 'context_set': ['']}, {'tag': 'diabetic retinopathy', 'patterns': ['gradually worsening vision', 'sudden vision loss', 'shapes floating in field of vision (floaters)', 'blurred vision', ' patchy vision', 'eye pain or redness'], 'responses': ['you might be suffering from diabetic retinopathy'], 'context_set': ['']}, {'tag': 'type 2 diabetes', 'patterns': ['rinating more often than usual, particularly at night', 'feeling very thirsty', 'feeling very tired', 'unexplained weight loss', 'itchiness around the genital area', 'cuts or wounds that heal slowly', 'blurred vision'], 'responses': ['you might be suffering from type 2 diabetes'], 'context_set': ['']}, {'tag': 'type 1 diabetes', 'patterns': ['feeling very thirsty', 'urinating more frequently than usual', 'urinating particularly at night', 'feeling very tired', 'weight loss', 'loss of muscle bulk', 'itchiness around the genital area', 'regular bouts of thrush', 'blurred vision', 'the lens of eye changing shape'], 'responses': ['you might be suffering from type 1 diabetes'], 'context_set': ['']}, {'tag': 'Hypoglycaemia', 'patterns': ['feeling shaky and irritable', 'sweating', 'tingling lips', 'feeling weak', 'feeling confused', 'hunger', 'nausea', 'feeling sick'], 'responses': ['you might be suffering from Hypoglycaemia (low blood glucose)'], 'context_set': ['']}, {'tag': 'Hyperglycaemia', 'patterns': ['extreme thirst', 'a dry mouth', 'blurred vision', 'drowsiness', 'need to pass urine frequently'], 'responses': ['you might be suffering from Hyperglycaemia (high blood glucose)'], 'context_set': ['']}, {'tag': 'diarrhoea', 'patterns': ['stomach cramps', 'nausea', 'vomiting', 'headache', 'loss of appetite'], 'responses': ['you might be suffering from diarrhoea'], 'context_set': ['']}, {'tag': 'Ebola', 'patterns': ['high temperature fever', 'headache', 'joint and muscle pain', 'sore throat', 'severe muscle weakness'], 'responses': ['you might be suffering from headache Ebola'], 'context_set': ['']}, {'tag': 'kidney cancer', 'patterns': ['extreme tiredness (fatigue) or anaemia', 'unintentional weight loss', 'a high temperature of 38C (100.4F) or above', 'night sweats', 'general sense of feeling unwell', 'swelling of the veins in the testicles (in men)', 'loss of appetite', 'high blood pressure (hypertension)'], 'responses': ['you might be suffering from kidney cancer'], 'context_set': ['']}, {'tag': 'glandular fever', 'patterns': ['a high temperature fever', 'sore throat', 'swollen glands', 'fatigue', 'extreme tiredness'], 'responses': ['you might be suffering from glandular fever'], 'context_set': ['']}, {'tag': 'hay fever', 'patterns': ['frequent sneezing', 'runny nose', ' blocked nose', 'itchy, red or watery eyes', 'itchy throat, mouth, nose and ears', 'cough'], 'responses': ['you might be suffering from hay fever'], 'context_set': ['']}, {'tag': 'fibromyalgia', 'patterns': ['widespread pain'], 'responses': ['you might be suffering from fibromyalgia'], 'context_set': ['']}, {'tag': 'eye cancer', 'patterns': ['shadows, flashes of light, or wiggly lines in your vision', 'blurred vision', 'a dark patch in eye', 'partial or total loss of vision', 'bulging of one eye', "lump on eyelid or in eye that's increasing in size", 'pain in or around eye'], 'responses': ['you might be suffering from eye cancer'], 'context_set': ['']}, {'tag': 'COVID-19', 'patterns': ['have a new cough that’s lasted for an hour', 'have had 3 or more episodes of coughing in 24 hours', 'are coughing more than usual', 'a new continuous cough', ' a fever/high temperature (37.8C or greater)'], 'responses': ['you might be suffering from COVID-19'], 'context_set': ['']}, {'tag': 'common cold', 'patterns': ['a sore throat', 'a blocked or runny nose', 'sneezing', 'a cough', 'a hoarse voice', 'generally feeling unwell'], 'responses': ['you might be suffering from common cold'], 'context_set': ['']}, {'tag': 'chickenpox', 'patterns': ['feeling sick', 'a high temperature (fever) of 38C (100.4F) or over', 'aching, painful muscles', 'headache', 'generally feeling unwell', 'loss of appetite'], 'responses': ['you might be suffering from chickenpox'], 'context_set': ['']}, {'tag': 'stroke', 'patterns': [' facial drooping', 'arm weakness', 'difficulty with speech', 'rapidly developing dizziness or balance', 'sudden numbness or weakness', 'loss of vision', 'confusion', ' severe headache'], 'responses': ['you might be suffering from stroke'], 'context_set': ['']}, {'tag': 'breast problems', 'patterns': ['  nipple discharge', 'unusual breast tenderness or pain', 'breast or nipple skin changes', 'lump or thickening in or near breast or in the underarm area.'], 'responses': ['you might be suffering from breast problems'], 'context_set': ['']}, {'tag': 'reproductive health problems', 'patterns': [' bleeding or spotting between periods', 'itching, burning, or irritation genital area', 'pain or discomfort during sex', 'heavy or painful menstrual bleeding', ' severe pelvic/abdominal pain', 'unusual vaginal discharge', 'feeling of fullness in the lower abdomen', ' frequent urination or urinary urgency'], 'responses': ['you might be suffering from reproductive health problems'], 'context_set': ['']}, {'tag': 'lung problems', 'patterns': ['  coughing up blood', 'shortness of breath', 'difficulty breathing', 'chronic cough', 'repeated bouts of bronchitis or pneumonia', 'wheezing.'], 'responses': ['you might be suffering from lung problems'], 'context_set': ['']}, {'tag': 'bladder problems', 'patterns': ['difficult or painful urination', 'frequent urination', 'loss of bladder control', 'blood in urine', 'waking frequently at night to urinate', 'wetting the bed at night', 'leaking urine.'], 'responses': ['you might be suffering from bladder problems'], 'context_set': ['']}, {'tag': 'eating or weight problems', 'patterns': ['extreme thirst', 'dehydration', 'excessive hunger', 'losing weight without trying', 'binging, vomiting', 'starvation', 'preoccupation with food and weight', 'distorted body image', 'compulsive exercise', 'abuse of laxatives or diet pills', 'depression'], 'responses': ['you might be suffering from eating or weight problems'], 'context_set': ['']}, {'tag': 'influenza', 'patterns': ['headache', 'pain in the head', 'cough', 'fever', 'snizing', 'runny nose', 'sore throat', 'pain in throat', 'itching throat'], 'responses': ['you might be suffering from influeza', 'you might be suffering from flu'], 'context_set': ['']}, {'tag': 'asthma', 'patterns': ['shortness of breath', 'chest pain or tightness', 'cough', 'snizing'], 'responses': ['you might be suffering from asthma'], 'context_set': ['']}, {'tag': 'hepatitis_B', 'patterns': ['abdominal pain', 'fever', 'dark urine', 'joint pain', 'loss of apetite', 'nausea and vomitting', 'weakness and fatigue', 'yellowing of skin', 'jaundice'], 'responses': ['you might be suffering from hepatitis_B'], 'context_set': ['']}, {'tag': 'Dengue', 'patterns': ['headache', 'fever', 'muscle pain', 'joint pain', 'pain behind eyes', 'nausea and vomitting', 'rashes', 'minor bleeding from gums or nose '], 'responses': ['you might be suffering from Dengue'], 'context_set': ['']}]}

Create dataframe for patterns and tags

In [3]:
def create_df():
    df=pd.DataFrame({'Pattern':[],'Tag':[]})
    return df
    
df=create_df()
df

Empty DataFrame
Columns: [Pattern, Tag]
Index: []

Extract data from file

In [4]:
def extract_json_info(json_file,df):
    for intent in json_file['intents']:
        for pattern in intent['patterns']:
            sentence_tag=[pattern,intent['tag']]
            df.loc[len(df.index)] = sentence_tag
    return df        
df=extract_json_info(intents,df)

## Explore data

In [5]:
df.head()

            Pattern       Tag
0                Hi  greeting
1       How are you  greeting
2  Is anyone there?  greeting
3             Hello  greeting
4          Good day  greeting

In [6]:
df.shape

(244, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, 0 to 243
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Pattern  244 non-null    object
 1   Tag      244 non-null    object
dtypes: object(2)
memory usage: 5.7+ KB

In [8]:
x=len(df['Tag'].unique())
print(f"{x} classes in or tags")

print(df['Tag'].unique())

37 classes in or tags
['greeting' 'name' 'problem_solving' 'jaundice' 'emotional problems'
 'headache problems' 'appendicitis' 'anal cancer' 'allergy'
 'alcohol-related liver disease' 'bladder cancer' 'dehydration'
 'diabetic retinopathy' 'type 2 diabetes' 'type 1 diabetes'
 'Hypoglycaemia' 'Hyperglycaemia' 'diarrhoea' 'Ebola' 'kidney cancer'
 'glandular fever' 'hay fever' 'fibromyalgia' 'eye cancer' 'COVID-19'
 'common cold' 'chickenpox' 'stroke' 'breast problems'
 'reproductive health problems' 'lung problems' 'bladder problems'
 'eating or weight problems' 'influenza' 'asthma' 'hepatitis_B' 'Dengue']

In [9]:
df.isna().sum()

Pattern    0
Tag        0
dtype: int64

Understand the corpus

In [10]:
def get_corpus(series):
    words = []
    for text in series:
        for word in text.split():
            words.append(word.strip())
    return words

corpus = get_corpus(df.Pattern)
corpus[:5]
# print(corpus)

['Hi', 'How', 'are', 'you', 'Is']

In [11]:
from collections import Counter
counter = Counter(corpus)
most_common = counter.most_common(10)
print(most_common)
most_common = dict(most_common)
most_common

[('of', 37), ('or', 33), ('a', 25), ('and', 24), ('in', 19), ('the', 18), ('feeling', 18), ('loss', 17), ('pain', 17), ('vision', 12)]

{'of': 37,
 'or': 33,
 'a': 25,
 'and': 24,
 'in': 19,
 'the': 18,
 'feeling': 18,
 'loss': 17,
 'pain': 17,
 'vision': 12}

Create another dataframe for patterns, tags and labels

In [12]:
df2 = df.copy()
df2.head()

            Pattern       Tag
0                Hi  greeting
1       How are you  greeting
2  Is anyone there?  greeting
3             Hello  greeting
4          Good day  greeting

Create list of unique tags as labels

In [13]:
labels=df2['Tag'].unique().tolist()
labels=[s.strip() for s in labels]
labels[:5]

['greeting', 'name', 'problem_solving', 'jaundice', 'emotional problems']

Create `id` to `label` and vise versa

In [14]:
id2label={id:label for id,label in enumerate(labels)}
label2id={label:id for id,label in enumerate(labels)}
num_labels=len(labels)

In [15]:
id2label

{0: 'greeting',
 1: 'name',
 2: 'problem_solving',
 3: 'jaundice',
 4: 'emotional problems',
 5: 'headache problems',
 6: 'appendicitis',
 7: 'anal cancer',
 8: 'allergy',
 9: 'alcohol-related liver disease',
 10: 'bladder cancer',
 11: 'dehydration',
 12: 'diabetic retinopathy',
 13: 'type 2 diabetes',
 14: 'type 1 diabetes',
 15: 'Hypoglycaemia',
 16: 'Hyperglycaemia',
 17: 'diarrhoea',
 18: 'Ebola',
 19: 'kidney cancer',
 20: 'glandular fever',
 21: 'hay fever',
 22: 'fibromyalgia',
 23: 'eye cancer',
 24: 'COVID-19',
 25: 'common cold',
 26: 'chickenpox',
 27: 'stroke',
 28: 'breast problems',
 29: 'reproductive health problems',
 30: 'lung problems',
 31: 'bladder problems',
 32: 'eating or weight problems',
 33: 'influenza',
 34: 'asthma',
 35: 'hepatitis_B',
 36: 'Dengue'}

In [16]:
label2id

{'greeting': 0,
 'name': 1,
 'problem_solving': 2,
 'jaundice': 3,
 'emotional problems': 4,
 'headache problems': 5,
 'appendicitis': 6,
 'anal cancer': 7,
 'allergy': 8,
 'alcohol-related liver disease': 9,
 'bladder cancer': 10,
 'dehydration': 11,
 'diabetic retinopathy': 12,
 'type 2 diabetes': 13,
 'type 1 diabetes': 14,
 'Hypoglycaemia': 15,
 'Hyperglycaemia': 16,
 'diarrhoea': 17,
 'Ebola': 18,
 'kidney cancer': 19,
 'glandular fever': 20,
 'hay fever': 21,
 'fibromyalgia': 22,
 'eye cancer': 23,
 'COVID-19': 24,
 'common cold': 25,
 'chickenpox': 26,
 'stroke': 27,
 'breast problems': 28,
 'reproductive health problems': 29,
 'lung problems': 30,
 'bladder problems': 31,
 'eating or weight problems': 32,
 'influenza': 33,
 'asthma': 34,
 'hepatitis_B': 35,
 'Dengue': 36}

Add converted `label2id` to df2

In [17]:
df2['labels'] = df2['Tag'].map(lambda x: label2id[x.strip()])
df2.head()

            Pattern       Tag  labels
0                Hi  greeting       0
1       How are you  greeting       0
2  Is anyone there?  greeting       0
3             Hello  greeting       0
4          Good day  greeting       0

In [18]:
X=list(df2['Pattern'])
X[:5]

['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day']

In [19]:
y=list(df2['labels'])
y[:5]

[0, 0, 0, 0, 0]

Define training and test datasets

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=100)

Define base model

In [21]:
model_name="bert-base-uncased"
max_len=256

Load tokenizer

In [22]:
tokenizer=BertTokenizer.from_pretrained(model_name,max_length=max_len)

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

Load model

In [23]:
model=BertForSequenceClassification.from_pretrained(model_name,num_labels=num_labels,id2label=id2label,label2id=label2id)

A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Define encoders

In [24]:
train_encoding=tokenizer(X_train,truncation=True,padding=True)
test_encoding=tokenizer(X_test,truncation=True,padding=True)

In [25]:
full_data = tokenizer(X, truncation=True, padding=True)

Data loader

In [26]:
class DataLoader(Dataset):
    
    def __init__(self, encodings, labels):
        
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
               
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):

        return len(self.labels)

In [27]:
train_dataloader = DataLoader(train_encoding, y_train)
test_dataloader = DataLoader(test_encoding, y_test)

In [28]:
fullDataLoader = DataLoader(full_data, y_test)

In [29]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

def compute_metrics(pred):
    labels = pred.label_ids  # True labels
    preds = pred.predictions.argmax(-1)  # Predicted labels (argmax along the last axis)

    # Using precision_recall_fscore_support to compute precision, recall, F1 score
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')

    # Using accuracy_score to compute accuracy
    acc = accuracy_score(labels, preds)
    
    # Returning a dictionary containing the computed metrics
    return {
        'Accuracy': acc,
        'F1': f1,
        'Precision': precision,
        'Recall': recall
    }

Define training arguments

In [30]:
training_args = TrainingArguments(
    output_dir='./output', 
    do_train=True,
    do_eval=True,
    num_train_epochs=100,              
    per_device_train_batch_size=32,  
    per_device_eval_batch_size=16,
    warmup_steps=100,                
    weight_decay=0.05,
    logging_strategy='steps',
    logging_dir='./logs',            
    logging_steps=50,
    evaluation_strategy="steps",
    eval_steps=50,
    save_strategy="steps", 
    load_best_model_at_end=True
)

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [31]:
trainer = Trainer(
    model=model,
    args=training_args,                 
    train_dataset=train_dataloader,         
    eval_dataset=test_dataloader,            
    compute_metrics= compute_metrics
)

In [32]:
%%time
trainer.train()

  0%|          | 0/600 [00:00<?, ?it/s]

{'loss': 3.5472, 'grad_norm': 6.391028881072998, 'learning_rate': 2.5e-05, 'epoch': 8.33}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.5535542964935303, 'eval_Accuracy': 0.04918032786885246, 'eval_F1': 0.014430014430014432, 'eval_Precision': 0.008815426997245178, 'eval_Recall': 0.0404040404040404, 'eval_runtime': 0.4748, 'eval_samples_per_second': 128.469, 'eval_steps_per_second': 8.424, 'epoch': 8.33}
{'loss': 2.8781, 'grad_norm': 5.743937015533447, 'learning_rate': 5e-05, 'epoch': 16.67}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.325455665588379, 'eval_Accuracy': 0.11475409836065574, 'eval_F1': 0.06594422043010753, 'eval_Precision': 0.06550595238095237, 'eval_Recall': 0.09635416666666666, 'eval_runtime': 0.2132, 'eval_samples_per_second': 286.122, 'eval_steps_per_second': 18.762, 'epoch': 16.67}
{'loss': 1.7409, 'grad_norm': 5.53952169418335, 'learning_rate': 4.5e-05, 'epoch': 25.0}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.283698797225952, 'eval_Accuracy': 0.11475409836065574, 'eval_F1': 0.0886154780891623, 'eval_Precision': 0.0891996891996892, 'eval_Recall': 0.10858585858585858, 'eval_runtime': 0.2018, 'eval_samples_per_second': 302.221, 'eval_steps_per_second': 19.818, 'epoch': 25.0}
{'loss': 0.8883, 'grad_norm': 3.1159462928771973, 'learning_rate': 4e-05, 'epoch': 33.33}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.3424973487854004, 'eval_Accuracy': 0.19672131147540983, 'eval_F1': 0.16791726791726794, 'eval_Precision': 0.1893939393939394, 'eval_Recall': 0.18181818181818182, 'eval_runtime': 0.2049, 'eval_samples_per_second': 297.689, 'eval_steps_per_second': 19.521, 'epoch': 33.33}
{'loss': 0.5343, 'grad_norm': 2.0825748443603516, 'learning_rate': 3.5e-05, 'epoch': 41.67}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.6063597202301025, 'eval_Accuracy': 0.18032786885245902, 'eval_F1': 0.1525252525252525, 'eval_Precision': 0.15656565656565655, 'eval_Recall': 0.17424242424242425, 'eval_runtime': 0.2016, 'eval_samples_per_second': 302.582, 'eval_steps_per_second': 19.841, 'epoch': 41.67}
{'loss': 0.4179, 'grad_norm': 3.9413092136383057, 'learning_rate': 3e-05, 'epoch': 50.0}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.8076369762420654, 'eval_Accuracy': 0.19672131147540983, 'eval_F1': 0.16099439775910368, 'eval_Precision': 0.16862745098039217, 'eval_Recall': 0.19852941176470587, 'eval_runtime': 0.211, 'eval_samples_per_second': 289.134, 'eval_steps_per_second': 18.96, 'epoch': 50.0}
{'loss': 0.3682, 'grad_norm': 2.7071311473846436, 'learning_rate': 2.5e-05, 'epoch': 58.33}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 3.990229845046997, 'eval_Accuracy': 0.18032786885245902, 'eval_F1': 0.15007215007215008, 'eval_Precision': 0.16017316017316016, 'eval_Recall': 0.19444444444444445, 'eval_runtime': 0.2066, 'eval_samples_per_second': 295.23, 'eval_steps_per_second': 19.359, 'epoch': 58.33}
{'loss': 0.3288, 'grad_norm': 2.113438844680786, 'learning_rate': 2e-05, 'epoch': 66.67}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 4.017853736877441, 'eval_Accuracy': 0.21311475409836064, 'eval_F1': 0.17296777296777296, 'eval_Precision': 0.17777777777777776, 'eval_Recall': 0.2121212121212121, 'eval_runtime': 0.2056, 'eval_samples_per_second': 296.751, 'eval_steps_per_second': 19.459, 'epoch': 66.67}
{'loss': 0.3246, 'grad_norm': 3.22538685798645, 'learning_rate': 1.5e-05, 'epoch': 75.0}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 4.102392673492432, 'eval_Accuracy': 0.21311475409836064, 'eval_F1': 0.17663690476190477, 'eval_Precision': 0.17819940476190477, 'eval_Recall': 0.21874999999999997, 'eval_runtime': 0.2128, 'eval_samples_per_second': 286.692, 'eval_steps_per_second': 18.799, 'epoch': 75.0}
{'loss': 0.3127, 'grad_norm': 1.7170655727386475, 'learning_rate': 1e-05, 'epoch': 83.33}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 4.128983974456787, 'eval_Accuracy': 0.19672131147540983, 'eval_F1': 0.1636904761904762, 'eval_Precision': 0.17559523809523808, 'eval_Recall': 0.20833333333333331, 'eval_runtime': 0.2027, 'eval_samples_per_second': 300.905, 'eval_steps_per_second': 19.731, 'epoch': 83.33}
{'loss': 0.2995, 'grad_norm': 2.432541608810425, 'learning_rate': 5e-06, 'epoch': 91.67}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 4.152102470397949, 'eval_Accuracy': 0.19672131147540983, 'eval_F1': 0.1636904761904762, 'eval_Precision': 0.17559523809523808, 'eval_Recall': 0.20833333333333331, 'eval_runtime': 0.2044, 'eval_samples_per_second': 298.41, 'eval_steps_per_second': 19.568, 'epoch': 91.67}
{'loss': 0.2909, 'grad_norm': 2.3220505714416504, 'learning_rate': 0.0, 'epoch': 100.0}

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'eval_loss': 4.167184352874756, 'eval_Accuracy': 0.19672131147540983, 'eval_F1': 0.15873015873015872, 'eval_Precision': 0.17027417027417027, 'eval_Recall': 0.20202020202020202, 'eval_runtime': 0.2169, 'eval_samples_per_second': 281.245, 'eval_steps_per_second': 18.442, 'epoch': 100.0}
{'train_runtime': 242.2419, 'train_samples_per_second': 75.544, 'train_steps_per_second': 2.477, 'train_loss': 0.9942811346054077, 'epoch': 100.0}
CPU times: user 3min 34s, sys: 15.2 s, total: 3min 49s
Wall time: 4min 2s

TrainOutput(global_step=600, training_loss=0.9942811346054077, metrics={'train_runtime': 242.2419, 'train_samples_per_second': 75.544, 'train_steps_per_second': 2.477, 'total_flos': 206956638702000.0, 'train_loss': 0.9942811346054077, 'epoch': 100.0})

Evaluate trainer

In [33]:
q=[trainer.evaluate(eval_dataset=df2) for df2 in [train_dataloader, test_dataloader]]
pd.DataFrame(q, index=["train","test"]).iloc[:,:5]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/johnmoses/miniconda3/envs/mconda38/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

       eval_loss  eval_Accuracy   eval_F1  eval_Precision  eval_Recall
train   0.279341       0.868852  0.871538        0.912862     0.859588
test    4.128984       0.196721  0.163690        0.175595     0.208333

Save model and tokenizer

In [34]:
model_path = "base"

In [35]:
trainer.save_model(model_path)
tokenizer.save_pretrained(model_path)

('base/tokenizer_config.json',
 'base/special_tokens_map.json',
 'base/vocab.txt',
 'base/added_tokens.json')

Load model and tokenizer

In [41]:
new_model = BertForSequenceClassification.from_pretrained(model_path)
new_tokenizer= BertTokenizerFast.from_pretrained(model_path)

In [37]:
pipe= pipeline("sentiment-analysis", model=new_model, tokenizer=new_tokenizer, device='mps')

In [38]:
pipe("Hello")

[{'label': 'greeting', 'score': 0.9569432139396667}]

## Predict

In [39]:
def predict(text):
    # Tokenize the input text and convert it to PyTorch tensors
    inputs = new_tokenizer(text, padding=True, truncation=True, max_length=512, return_tensors="pt").to("cpu")

    # Pass the input tensors through the model
    outputs = new_model(**inputs)

    # Softmax the output to get probabilities
    probs = outputs[0].softmax(1)

    # Get the predicted label index
    pred_label_idx = probs.argmax()

    # Convert the predicted label index to the actual label using model configuration
    pred_label = new_model.config.id2label[pred_label_idx.item()]

    return pred_label

In [42]:
text = "Hello"
predict(text)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

'greeting'

In [43]:
def model_response(text):
    response = ''
    score = pipe(text)[0]['score']
    tag = pipe(text)[0]['label']
    if score < 0.8:
        response += "Don't understand"
    else:
        label = new_model.config.label2id[pipe(text)[0]['label']]
        response = random.choice(intents['intents'][label]['responses'])
    return response, tag

In [45]:
model_response('hi')

('Hello!', 'greeting')